# utils/bug_reporter.py
import os
import time
from datetime import datetime
from pathlib import Path
from utils.ai_helper import analyze_failure

REPORTS_DIR = Path("reports")
REPORTS_DIR.mkdir(exist_ok=True)

def _timestamp():
    return datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")

def write_bug_report(test_name: str, error_message: str, screenshot_path: str | None = None, html_snippet: str | None = None, extra_steps: list | None = None):
    """
    Create a markdown bug report and return its path.
    - test_name: short name of the test
    - error_message: raw exception / assertion text
    - screenshot_path: relative path to screenshot file (if any)
    - html_snippet: small HTML/text context
    - extra_steps: list of human-readable steps to reproduce
    """
    ts = _timestamp()
    safe_name = test_name.replace(" ", "_")
    filename = REPORTS_DIR / f"bug_{safe_name}_{ts}.md"

    # Ask AI for analysis (this will return fallback text if AI not available)
    ai_text = analyze_failure(error_message, html_snippet)

    # Basic structured content
    title = f"Bug: {test_name} - {ts}"
    steps_md = "\n".join(f"- {s}" for s in (extra_steps or ["Open test environment", "Run the failing test script", "Observe failure"]))

    md = [
        f"# {title}",
        "",
        f"**Timestamp (UTC):** {ts}",
        f"**Test:** {test_name}",
        "",
        "## Steps to Reproduce",
        steps_md,
        "",
        "## Expected",
        "- The test should pass and show success message",
        "",
        "## Actual",
        f"- {error_message}",
        "",
    ]

    if screenshot_path:
        md += [f"## Screenshot\n![]({screenshot_path})\n"]

    if html_snippet:
        md += ["## HTML Snippet", "```html", html_snippet[:4000], "```", ""]

    md += ["## AI Analysis (root cause / suggestions)", ai_text, ""]

    md += ["---", f"Generated by Jagadeesh AI Automation Engine"]

    with open(filename, "w", encoding="utf-8") as fh:
        fh.write("\n".join(md))

    return str(filename)
